import { test, expect } from '@playwright/test';

const testTitles = [
    'test navigation to home page',
    'test navigation to product category page',
    'test navigation to product details page from search results',
    'verify back button functionality on product details page',
    'verify navigation menu links functionality',
    'test redirection from http to https',
    'verify external links open in new tab',
    'test navigation to about us page',
    'test navigation to contact page',
    'verify navigation to login page',
    'test navigation to registration page',
    'verify navigation to support page',
    'test navigation to careers page',
    'test navigation to faq page',
    'verify navigation to privacy policy page',
    'test navigation to terms of service page',
    'verify navigation to checkout page',
    'test navigation to cart page',
    'verify navigation to account settings page',
    'test navigation to order history page',
    'verify navigation to profile page',
    'test navigation to wishlist page',
    'verify navigation to search results page',
    'test navigation to blog page',
    'test navigation to promotions page',
    'verify navigation to product comparison page',
    'test navigation to featured products section',
    'test navigation to best sellers section',
    'verify navigation to new arrivals section',
    'test navigation to sale items section',
    'test navigation to recommended products section',
    'verify navigation to footer links',
    'test navigation to help and support section',
    'verify navigation to social media links',
    'test navigation to subscribe section',
    'test navigation to newsletter signup form',
    'verify navigation to account login from header',
    'test navigation to account registration from header',
    'verify navigation to account settings from header',
    'test navigation to cart from header',
    'verify navigation to wishlist from header',
    'test navigation to promotions from header',
    'verify navigation to search from header',
    'test navigation to account settings from footer',
    'verify navigation to order history from footer',
    'test navigation to contact us from footer',
    'verify navigation to privacy policy from footer',
    'test navigation to terms of service from footer',
    'verify navigation to about us from footer',
    'test navigation to careers from footer',
    'verify navigation to faq from footer',
    'test navigation to blog from footer',
    'verify navigation to social media links from footer',
    'test navigation to help and support from footer',
    'verify navigation to subscribe from footer',
    'test navigation to featured products from home page',
    'verify navigation to best sellers from home page',
    'test navigation to new arrivals from home page',
    'verify navigation to sale items from home page',
    'test navigation to recommended products from home page',
    'verify navigation to footer links from home page',
    'test navigation to help and support from home page',
    'verify navigation to social media links from home page',
    'test navigation to subscribe from home page',
    'verify navigation to account settings from home page',
    'test navigation to recommended products from product category page',
    'verify navigation to account settings from product category page',
]

testTitles.forEach(testTitle => {
    test(testTitle, async ({ page }) => {
        await page.goto('https://playwright.dev/');
        await expect(page).toHaveTitle(/Playwright/);
        await page.getByRole('link', { name: 'Get started' }).click();
        await expect(page).toHaveURL(/.*intro/);
    });
});
